const ShapesActionTypes = {
	FETCH_SHAPES_START: 'FETCH_SHAPES_START',
	FETCH_SHAPES_SUCCESS: 'FETCH_SHAPES_SUCCESS',
	FETCH_SHAPES_FAILURE: 'FETCH_SHAPES_FAILURE',
	TOGGLE_FILTERED_SHAPE: 'TOGGLE_FILTERED_SHAPE',
};

export default ShapesActionTypes;
