const ShapesActionTypes = {
	FETCH_SHAPES_START: 'FETCH_SHAPES_START',
	FETCH_SHAPES_SUCCESS: 'FETCH_SHAPES_SUCCESS',
	FETCH_SHAPES_FAILURE: 'FETCH_SHAPES_FAILURE',
};

export default ShapesActionTypes;
